 version: '2'
 services:

   db1:
    image: mysql:5.7
    restart: always
    ports:
      - 3310:3306
    environment:
     MYSQL_ROOT_PASSWORD: icoder_pwd
     MYSQL_DATABASE: icoder_db
     MYSQL_USER: icoder_user
     MYSQL_PASSWORD: icoder_pwd

   db2:
     image: mysql:5.7
     restart: always
     ports:
       - 3311:3306
     environment:
      MYSQL_ROOT_PASSWORD: icoder_pwd
      MYSQL_DATABASE: icoder_db
      MYSQL_USER: icoder_user
      MYSQL_PASSWORD: icoder_pwd